---
sidebar: sidebar 
permalink: concept-storage-fleets.html 
keywords: storage fleets, fleet management, storage organization, folders, ONTAP, clusters, storage systems, resource grouping, delegated administration, fleet design, netapp console local 
summary: 存储群组对您在 NetApp Console 本地部署中共同管理的存储系统进行分组。使用文件夹对相关群组进行分组。您可以在所需范围内应用策略、授予访问权限和监控运行状况。 
---
= 了解 NetApp Console 本地部署中的存储机群
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
存储群组对您在 NetApp Console 本地部署中共同管理的存储系统进行分组。使用文件夹对相关群组进行分组。您可以在所需范围内应用策略、授予访问权限和监控运行状况。



[[why-fleets-matter]]
== 为何需要关注机群

随着存储环境的增长，单独管理单个集群变得不切实际。Fleet 为您提供了一种结构化的方式来对相关存储系统进行分组，以便您可以将其作为一个整体进行操作。无需逐个集群配置策略或访问控制，只需在 fleet 级别应用一次即可。这减少了重复的管理工作，并确保 fleet 中的每个集群都按照相同的标准运行。



[[how-folders-and-fleets-organize-your-resources]]
== 文件夹和队列如何组织您的资源

组织的资源层次结构由文件夹和队列组成。文件夹对相关队列进行分组，队列对存储系统进行分组。

* *组织*是层次结构的顶层，代表您的公司。
* *文件夹*可帮助您组织相关的队列。例如，您可以为每个地区或业务部门创建一个文件夹，然后在每个文件夹中创建队列。文件夹可以包含其他文件夹或队列，但不能与存储系统直接关联。当您将角色分配给文件夹级别的成员时，该成员将继承文件夹中所有队列的角色。
* *队列*将您统一管理的存储系统分组。您将存储系统与队列关联，并将成员分配给队列以授予其访问权限。



NOTE: 文件夹是一种组织工具，对没有 IAM 权限的成员（如组织管理员或文件夹或舰队管理员角色）不可见。成员访问的是舰队，而不是文件夹。



[[fleet-examples]]
== Fleet 示例

如何组织集群取决于您的运营模式。常见方法包括：

* *按环境* 为生产、开发和测试工作负载创建单独的队列。这样可以使生产存储受到更严格的性能和容量策略约束，同时在较低级别的环境中保持更大的灵活性。
* *按业务部门* 将服务于特定部门（财务、工程或人力资源）的集群归入专用机群。然后，您可以将存储管理职责分配给该业务部门内的团队成员，而无需向他们公开其他机群。
* *按位置或数据中心* 当集群分布在各站点时，按位置组织可监控站点级别的运行状况、应用特定区域的分层策略，并跟踪每个站点的容量消耗。
* *按应用程序层* 对托管特定类别工作负载（数据库、文件共享或虚拟机）的集群进行分组，以便您可以在整个集群组中应用针对该工作负载性能配置文件进行调整的存储类。



TIP: 使用文件夹添加另一个级别的组织。例如，为每个区域创建一个文件夹，然后在每个区域文件夹内创建基于环境的舰队。



[[how-fleets-connect-to-storage-classes]]
== 车队如何连接到存储类

当您将存储类与群组关联时，Console 本地部署会将该类中的策略应用于群组内的所有存储资源调配。在群组内调配的工作负载会自动继承存储类中定义的性能、容量和分层规则，而无需管理员在调配时选择或验证策略设置。这使得群组成为在服务于共同目的的集群中强制执行一致存储行为的主要方式。



[[how-folders-and-fleets-support-access-control-and-visibility]]
== 文件夹和队列如何支持访问控制和可见性

文件夹和车队作为用户访问的边界：

* 当您在*文件夹*级别分配角色时，成员将继承该文件夹中所有队列和资源的相应角色。这允许组织管理员通过创建文件夹并分配文件夹或队列管理员角色来委派管理职责。这些管理员随后可以管理其文件夹中的所有队列，而无需访问整个组织。
* 当您在*fleet* 级别分配角色时，该成员只能访问该 fleet 内的存储系统。


这使您可以将存储管理委派给团队成员或应用程序所有者，而无需授予他们对基础架构中无关部分的可见性。Console 本地部署提供集群级运行状况和性能监控，因此您可以从单个视图中查看集群中所有集群的状态，尽早识别问题，并在影响工作负载之前采取行动。
