---
sidebar: sidebar 
permalink: reference-iam-storage-roles.html 
keywords: storage roles, Storage admin, Storage viewer, System health specialist, ONTAP management, storage governance, identity and access management, access roles, rbac, netapp console local 
summary: 您可以将以下角色分配给用户，以便为他们提供对 NetApp Console 本地部署中存储管理功能的访问权限。您可以为用户分配用于管理存储的管理角色或用于监控的查看器角色。 
---
= 适用于 NetApp Console 本地部署的存储访问角色
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以将以下角色分配给用户，以便为他们提供对 NetApp Console 本地部署中存储管理功能的访问权限。您可以为用户分配用于管理存储的管理角色或用于监控的查看器角色。

管理员可以将以下存储资源和功能的存储角色分配给用户：

存储资源：

* 本地 ONTAP 集群


控制台服务和功能：

* 存储健康功能


.NetApp Console 本地部署中的存储角色示例
XYZ Corporation是一家跨国公司，拥有庞大的存储工程师和存储管理员团队。他们允许该团队管理其区域的存储资产，同时限制对用户管理和许可证管理等核心 Console 本地部署任务的访问。

在一个由 12 人组成的团队中，两个用户被赋予 *Storage viewer* 角色，允许他们监控与分配给他们的 Console 本地部署队列相关联的存储资源。其余九个用户被赋予 *Storage admin* 角色，该角色包括管理软件更新、通过 Console 本地部署访问 ONTAP System Manager 以及发现存储资源（添加系统）的能力。团队中的一个人被赋予 *System health specialist* 角色，以便他们可以管理其所在区域中存储资源的运行状况，但不能修改或删除任何系统。此人还可以对分配给他们的队列的存储资源执行软件更新。

该组织还有另外两个具有 *Organization admin* 角色的用户，他们可以管理 Console 本地部署的所有方面，包括用户管理和许可证管理，以及几个具有 *Folder or fleet admin* 角色的用户，他们可以为分配给他们的文件夹和机群执行 Console 本地部署管理任务。

下表显示了每个存储角色执行的操作。

[cols="40,20a,20a,20a"]
|===
| 功能和操作 | 存储管理员 | 系统运行状况专家 | 存储查看器 


4+| *存储管理*： 


| 发现新资源（添加系统）  a| 
是
 a| 
是
 a| 
否



| 查看已添加的系统  a| 
是
 a| 
是
 a| 
否



| 从 Console 中删除系统  a| 
是
 a| 
否
 a| 
否



| 修改系统  a| 
是
 a| 
否
 a| 
否



4+| *System Manager 访问* 


| 可以输入凭据  a| 
是
 a| 
是
 a| 
否

|===