---
sidebar: sidebar 
permalink: task-audit-console-activity.html 
keywords: administer, monitor, timeline, notifications, alerts, events, notification center, email, audit page, audit action 
summary: '您可以从"审核"页面审核用户活动（从 UI 和 API 启动），还可以监视 Console 正在执行的操作的状态，以查看是否存在任何需要解决的问题。您可以从"审核"页面查看状态，或将审核日志配置为发送到您自己的 syslog 服务器。' 
---
= 审核 NetApp Console 本地部署活动
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在合规性审查期间记录管理活动，以验证访问权限更改并保留整个 NetApp Console 本地部署的操作记录。

.必需角色
超级管理员、组织管理员、文件夹和车队管理员、运营支持分析师、超级查看者、组织查看者或文件夹和车队查看者。link:reference-iam-predefined-roles.html["了解访问角色"]。

您可以在 Console 本地部署中查看审计活动，并下载审计日志的 CSV 文件。



[[audit-user-activity-from-the-audit-page]]
== 从"审核"页面审核用户活动

在解决事件或验证运营责任时，监控管理活动以跟踪整个 NetApp Console 本地部署的更改。

"审核"页面显示用户在组织内完成的操作。例如，您可以验证谁向组织添加了成员、确认用户是否删除了 fleet，或查看用户在组织中执行的其他存储管理操作。

审核日志显示以下服务的活动：

* 租用：与管理组织相关的操作，例如添加用户、创建队列以及关联资源。
* 存储管理：与管理存储资源相关的操作。
* 联合身份验证：与管理联合身份验证相关的操作，例如创建联合身份验证以及添加或删除联合身份验证组织。


.步骤
. 选择 *Administration > Audit*。
. 使用表格上方的筛选器可按时间范围、服务、操作、资源、用户或状态缩小审核活动范围。


审核条目显示在可以解析用户身份时执行操作的用户。如果无法解析用户的身份，条目将显示用户的 `auth0Id`而不是其姓名。

+ 例如，您可以使用 *Service* 筛选器显示与特定服务相关的操作，也可以使用 *User* 筛选器显示与特定用户帐户相关的操作。



[[filter-audit-logs-for-identity-and-access-management-actions]]
=== 筛选身份和访问管理操作的审核日志

查看访问管理更改，以确认谁修改了组织资源，并支持准确的安全调查。

.步骤
. 选择 *Administration > Audit*。
. 使用筛选器缩小结果范围。选择 *Service*，然后选择 *Tenancy*。
. 使用任何其他筛选器进一步细化结果。
+
例如，使用 *User* 筛选器显示特定用户帐户执行的 IAM 操作。





[[download-audit-logs-from-the-audit-page]]
=== 从审核页面下载审核日志

保留组织行动的独立记录，以支持合规审查和未来的事件调查。下载的 CSV 文件包括所有审核日志列，即使您应用筛选器或更改显示的列也是如此。

.步骤
. 在*审核*页面中，选择表格右上角的下载图标。

