---
sidebar: sidebar 
permalink: task-iam-active-directory-integrate.html 
keywords: AD, Active Directory, LDAP, directory services, directory users, authentication, user management, netapp console 
summary: 将 NetApp Console 本地部署与 Active Directory 集成，以实现目录支持的登录和用户查找。 
---
= 将 NetApp Console 本地部署与 Active Directory 集成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
将 NetApp Console 本地部署与 Active Directory 集成，以进行目录支持的登录和用户查找。使用目录服务对用户进行身份验证，然后在 NetApp Console 本地部署中将访问权限分配给这些用户。

.必需的访问角色
超级管理员或组织管理员。link:reference-iam-predefined-roles.html["了解访问角色"]。

与 Active Directory 集成时，Console 本地部署将通过现有目录对用户进行身份验证。添加目录用户后，分配 Console 访问角色以控制该用户可以访问的内容。

Active Directory 集成还可以通过将现有控件、审计跟踪和策略应用于 Console 本地部署访问，帮助您满足合规性要求。

[NOTE]
====
* Active Directory 集成不会创建联合组，不会同步目录组分配，也不会自动授予访问权限。管理员仍会将目录用户添加到组织并在 Console 本地部署中分配角色。
* 一次仅支持一个 Active Directory 集成。配置集成后，*添加集成* 按钮将被禁用。要切换到其他目录，请先禁用或删除现有集成。
* 目录用户不配置或使用多重身份验证 (MFA)。Console 本地部署仅为本地用户支持 MFA。link:task-manage-member-security.html["了解如何管理成员安全设置"]。


====


[[before-you-begin]]
== 开始之前

在与 Active Directory 集成之前，请确认您已：

* 可以查询目录的Active Directory域和凭据
* LDAP 服务器地址和目录树的基本可分辨名称 (DN)
* 从 Console 本地部署到 LDAP 服务器的端口 389（LDAP）或 636（LDAPS）的网络访问
* SSL/TLS 证书（如果您计划使用 LDAPS）


.步骤
. 选择 *Administration > Identity and access*。
. 选择*目录服务*以打开联盟页面。
. 选择*添加集成*。
. 输入 Active Directory 服务器的连接详细信息：
+
** 集成的描述性名称。
** *LDAP 主机*：您的 LDAP 服务器的主机名或 IP 地址。对于多台服务器，请输入主服务器。
** 端口：LDAP 为 389，LDAPS 为 636。
** *连接超时*以毫秒为单位。默认值为 1000 毫秒。


. 选择 *Use SSL/TLS* 以使用 LDAPS。确认您的 LDAP 服务器支持 LDAPS，并且控制台可以访问所需的证书。
. 测试连接。如果失败，请检查 LDAP 主机、端口、网络连接和 SSL/TLS 证书。
. 测试成功后，输入目录和用户详细信息：
+
** *Base DN binding*：输入此应用程序将用于连接到目录的 LDAP/AD 帐户的绑定 DN，并输入该帐户的绑定凭据（密码）。Console 使用这些详细信息绑定到 LDAP 并验证连接。
** *用户 DN*：有权查询目录的用户帐户。例如， `CN=ldap-reader,OU=Service Accounts,DC=example,DC=com`。


. 选择*添加*以保存此集成。


.完成后
保存集成后，向组织添加目录用户并分配角色。添加目录用户之前，必须配置并启用至少一个 Active Directory 集成。link:task-iam-manage-members-permissions.html["了解如何添加目录用户并分配角色"]。



[[disable-or-enable-an-active-directory-integration]]
== 禁用或启用 Active Directory 集成

禁用集成以暂时挂起目录支持的身份验证，而不删除配置。禁用目录服务时，目录用户无法通过目录登录。

.步骤
. 选择 *Administration > Identity and access*。
. 选择*目录服务*以打开联盟页面。
. 在集成列表中，找到该集成，然后选择该行的操作菜单。
. 选择*禁用*以暂停集成，或选择*启用*以恢复集成。




[[delete-an-active-directory-integration]]
== 删除 Active Directory 集成

删除集成以永久删除目录服务配置。在删除之前，请查看有关链接到集成的目录用户的任何警告，因为他们的访问权限将受到影响。

.步骤
. 选择 *Administration > Identity and access*。
. 选择*目录服务*以打开联盟页面。
. 在集成列表中，找到该集成，然后选择该行的操作菜单。
. 选择 *Delete* 并确认删除。

