---
sidebar: sidebar 
permalink: task-audit-console-activity.html 
keywords: administer, monitor, timeline, notifications, alerts, events, notification center, email, audit page, audit action 
summary: '您可以从"审核"页面审核用户活动（从 UI 和 API 启动），还可以监视 Console 正在执行的操作的状态，以查看是否存在任何需要解决的问题。您可以从"审核"页面查看状态，或将审核日志配置为发送到您自己的 syslog 服务器。' 
---
= 审核 NetApp Console 本地部署活动
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以从"审核"页面审核从UI和API启动的用户活动，还可以监视NetApp Console本地部署中的操作状态以及启动这些操作的用户。

.必需角色
超级管理员、组织管理员、文件夹和车队管理员、运营支持分析师、超级查看者、组织查看者或文件夹和车队查看者。link:reference-iam-predefined-roles.html["了解访问角色"]。

您可以在 Console 本地部署中查看审核活动，下载审核日志的 CSV，或通过使用 webhook 将审核日志配置为发送到您自己的 syslog 服务器。



[[audit-user-activity-from-the-audit-page]]
== 从"审核"页面审核用户活动

使用"审核"页面可识别执行操作的人员或其状态。

"审核"页面显示用户在组织内完成的操作。例如，您可以验证是谁向组织添加了成员或已成功删除了舰队，以及查看用户在组织中执行的其他存储管理操作。

审核日志显示以下服务的活动：

* 租用：与管理组织相关的操作，例如添加用户、创建队列以及关联资源。
* 存储管理：与管理存储资源相关的操作。
* 联合身份验证：与管理联合身份验证相关的操作，例如创建联合身份验证以及添加或删除联合身份验证组织。


.步骤
. 选择 *Administration > Audit*。
. 使用表格上方的筛选器更改表格中显示的操作。
+
例如，您可以使用*服务*筛选器显示与特定服务相关的操作，也可以使用*用户*筛选器显示与特定用户帐户相关的操作。





[[filter-audit-logs-for-identity-and-access-management-actions]]
=== 筛选身份和访问管理操作的审核日志

要仅查看与管理组织相关的操作（例如添加成员、创建队列或删除资源），请按 Tenancy 服务筛选审核日志。

.步骤
. 选择 *Administration > Audit*。
. 使用筛选器缩小结果范围。选择 *Service*，然后选择 *Tenancy*。
. 使用任何其他筛选器进一步细化结果。
+
例如，使用 *User* 筛选器显示特定用户帐户执行的 IAM 操作。





[[download-audit-logs-from-the-audit-page]]
=== 从审核页面下载审核日志

您可以将审核日志从"审核"页面下载到 CSV 文件中。这使您能够记录用户在组织中执行的操作。下载的 CSV 文件包括所有审核日志列，无论"审核"页面上的过滤器或显示的列如何。

.步骤
. 在*审核*页面中，选择表格右上角的下载图标。

