---
sidebar: sidebar 
permalink: task-analyzer-volume-capacity-investigate.html 
keywords: capacity, snapshot, storage efficiency, forecast, almost full, workload analyzer, netapp console local deployment 
summary: 使用 Workload Analyzer 调查卷的容量和快照增长情况，以了解物理空间、存储效率和快照保留趋势。 
---
= 调查 NetApp Console 本地部署中卷的容量增长
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 NetApp Console 本地部署中的 Workload Analyzer 来调查卷空间不足的原因。

当卷正在填充或快照副本占用的空间超过预期时，请检查一段时间内的容量和快照趋势。容量分析部分显示物理空间和可用空间的变化情况、存储效率节省的细分，以及卷何时将达到容量阈值的预测。

如果您从警报或卷清单中打开分析器，则该卷已被选中，您可以专注于容量趋势和预测窗口。

.步骤
. 使用以下方法之一打开 Workload Analyzer：
+
** 从 *Health* 菜单中，选择 *Workload Analyzer*，然后在 *Volume* 字段中搜索并选择要调查的卷。
** 从 *Storage > Fleets > Inventory* 页面，导航到要分析的卷，然后从操作菜单中选择 *Analyze*。
** 从 *Alerts > Overview* 页面中，为要调查的卷选择一个警报，然后从警报详细信息中选择 *Analyze*。


. 设置*时间范围*以覆盖容量增长期间，然后选择*分析*。
. 滚动到*容量分析*部分。
. 从*视图*下拉列表中选择*容量视图*。
+
图表显示物理容量为底部堆叠区域，可用容量为顶部堆叠区域。两者之和等于总卷大小，因此您可以看到可用空间减少的速度有多快。

. 将鼠标悬停在图表上的某个点，可查看存储效率明细，包括重复数据删除、压缩和数据缩减节省量，以及总体存储效率比率。
+
在物理容量增加的同时，效率比率下降可能表明新写入的数据的重复数据删除或压缩效果不如现有数据。

. 要调查快照消耗情况，请从*View*下拉列表中选择*Snapshot View*。
+
图表将快照预留空间显示为水平参考线，快照已用容量作为其下方的区域。悬停可查看已使用的快照空间及其占预留空间的百分比、快照总数以及最旧快照的时间。

+
当快照消耗量超过预留空间时，快照开始占用卷数据区域中的空间，这会减少可用于新写入的空间。

. 如果卷将数据分层到云，请从*视图*下拉列表中选择*云层视图*，以比较本地性能层与云容量层的容量。
. 启用*显示预测*以预测卷何时将达到警告或临界容量阈值。
+
容量预测至少需要 10 天的历史数据。当卷满之前剩余容量不足 30 天时，分析器会将存储标识为接近已满。预测会显示一条包含预计突破时间的洞察消息。



.完成后
使用您观察到的容量趋势来决定接下来要做什么：

* 如果可用容量正趋向于满，请考虑增加卷大小、启用自动增长或将数据从卷移出。
* 如果快照已用容量超出保留容量，请查看您的快照策略和保留以回收空间。
* 如果存储效率比率正在下降，请检查工作负载的数据类型或内联效率设置是否正在减少节省。使用 link:reference-workload-analyzer-metrics.html["了解 NetApp Console 本地部署中的 Workload Analyzer 指标"] 获取容量、快照和效率指标的详细描述。

