= 
:allow-uri-read: 


.开始之前
您应该具备以下条件：

* 安装代理的根权限。
* 有关代理服务器的详细信息（如果代理需要通过代理服务器访问互联网）。
+
您可以选择在安装后配置代理服务器，但这样做需要重新启动代理。

* CA 签名的证书（如果代理服务器使用 HTTPS 或代理是拦截代理）。


.关于此任务
NetApp 支持站点上提供的安装程序可能是早期版本。安装后，如果有新版本可用，代理将自动更新。

.步骤
. 如果在主机上设置了_http_proxy_或_https_proxy_系统变量，请将其删除：
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
如果不删除这些系统变量，安装将失败。

. 从 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp 支持站点"^]下载代理软件，然后将其复制到 Linux 主机。
+
您应该下载用于您的网络或云端的"在线"代理安装程序。

. 分配运行此脚本的权限。
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
其中<version>是您下载的代理版本。

. 运行安装脚本。
+
[source, cli]
----
 ./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
--proxy 和 --cacert 参数是可选的。如果您有代理服务器，则需要输入所示的参数。安装程序不会提示您提供有关代理的信息。

+
以下是使用两个可选参数的命令示例：

+
[source, cli]
----
 ./NetApp-Console-Agent-v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy 使用以下格式之一将代理配置为使用 HTTP 或 HTTPS 代理服务器：

+
** \http://address:port
** \http://user-name:password@address:port
** \http://domain-name%92user-name:password@address:port
** \https://address:port
** \https://user-name:password@address:port
** \https://domain-name%92user-name:password@address:port
+
请注意以下事项：

+
*** 此用户可以是本地用户或域用户。
*** 对于域用户，您必须使用 \ 的 ASCII 码，如上所示。
*** 代理不支持包含 @ 字符的用户名或密码。
*** 如果密码中包含以下任何特殊字符，则必须通过在其前面加反斜杠来转义该特殊字符：& or !
+
例如：

+
\http://bxpproxyuser:netapp1\!@address:3128





+
--cacert 指定用于代理和代理服务器之间 HTTPS 访问的 CA 签名证书。仅当指定 HTTPS 代理服务器或代理是拦截代理时，才需要此参数。

. 如果您使用 Podman，则需要调整 aardvark-dns 端口。
+
.. 通过 SSH 连接到代理虚拟机。
.. 打开 podman _/usr/share/containers/containers.conf_ 文件并修改 Aardvark DNS 服务所选的端口。例如，将其更改为 54。
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. 重新启动代理虚拟机。




. 等待安装完成。
+
在安装结束时，如果指定了代理服务器，则代理服务 (occm) 将重新启动两次。

. 从连接到代理虚拟机的主机打开 Web 浏览器，并输入以下 URL：
+
https://_ipaddress_[]

. 登录后，设置代理：
+
.. 指定要与代理关联的 Console 组织。
.. 输入系统的名称。
.. 在*您是否在安全环境中运行？*下，保持限制模式禁用状态。
+
您应保持限制模式处于禁用状态，因为这些步骤描述了如何在标准模式下使用 Console。仅当您拥有安全环境并希望断开此帐户与 Console 后端服务的连接时，才应启用限制模式。如果是这种情况，link:task-quick-start-restricted-mode.html["按照步骤在受限模式下开始使用 NetApp Console"]。

.. 选择*Let's start*。



